/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.ui;

import com.google.inject.Injector;
import dk.sdu.mmmi.mdsd.MathIntAssignment.ui.internal.MathIntAssignmentActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MathIntLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(MathIntAssignmentActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		MathIntAssignmentActivator activator = MathIntAssignmentActivator.getInstance();
		return activator != null ? activator.getInjector(MathIntAssignmentActivator.DK_SDU_MMMI_MDSD_MATHINTLANGUAGE) : null;
	}

}
