/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.parser.antlr;

import com.google.inject.Inject;
import dk.sdu.mmmi.mdsd.parser.antlr.internal.InternalMathIntLanguageParser;
import dk.sdu.mmmi.mdsd.services.MathIntLanguageGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MathIntLanguageParser extends AbstractAntlrParser {

	@Inject
	private MathIntLanguageGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMathIntLanguageParser createParser(XtextTokenStream stream) {
		return new InternalMathIntLanguageParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "MathExp";
	}

	public MathIntLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MathIntLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
