/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MathIntLanguageUiModule extends AbstractMathIntLanguageUiModule {
  public Class<? extends IEObjectHoverProvider> bindIEObjectHoverProvider() {
    return ExpressionsEObjectHoverProvider.class;
  }
  
  public MathIntLanguageUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
