/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.ui.tests;

import com.google.inject.Injector;
import dk.sdu.mmmi.mdsd.MathIntAssignment.ui.internal.MathIntAssignmentActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MathIntLanguageUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MathIntAssignmentActivator.getInstance().getInjector("dk.sdu.mmmi.mdsd.MathIntLanguage");
	}

}
