/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Relation#getFromType <em>From Type</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Relation#getFromName <em>From Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Relation#isFromMultiple <em>From Multiple</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Relation#getToName <em>To Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Relation#isToMultiple <em>To Multiple</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Relation#getToType <em>To Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRelation()
 * @model
 * @generated
 */
public interface Relation extends Declaration
{
  /**
   * Returns the value of the '<em><b>From Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From Type</em>' reference.
   * @see #setFromType(Entity)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRelation_FromType()
   * @model
   * @generated
   */
  Entity getFromType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Relation#getFromType <em>From Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From Type</em>' reference.
   * @see #getFromType()
   * @generated
   */
  void setFromType(Entity value);

  /**
   * Returns the value of the '<em><b>From Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From Name</em>' attribute.
   * @see #setFromName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRelation_FromName()
   * @model
   * @generated
   */
  String getFromName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Relation#getFromName <em>From Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From Name</em>' attribute.
   * @see #getFromName()
   * @generated
   */
  void setFromName(String value);

  /**
   * Returns the value of the '<em><b>From Multiple</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From Multiple</em>' attribute.
   * @see #setFromMultiple(boolean)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRelation_FromMultiple()
   * @model
   * @generated
   */
  boolean isFromMultiple();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Relation#isFromMultiple <em>From Multiple</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From Multiple</em>' attribute.
   * @see #isFromMultiple()
   * @generated
   */
  void setFromMultiple(boolean value);

  /**
   * Returns the value of the '<em><b>To Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>To Name</em>' attribute.
   * @see #setToName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRelation_ToName()
   * @model
   * @generated
   */
  String getToName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Relation#getToName <em>To Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To Name</em>' attribute.
   * @see #getToName()
   * @generated
   */
  void setToName(String value);

  /**
   * Returns the value of the '<em><b>To Multiple</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>To Multiple</em>' attribute.
   * @see #setToMultiple(boolean)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRelation_ToMultiple()
   * @model
   * @generated
   */
  boolean isToMultiple();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Relation#isToMultiple <em>To Multiple</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To Multiple</em>' attribute.
   * @see #isToMultiple()
   * @generated
   */
  void setToMultiple(boolean value);

  /**
   * Returns the value of the '<em><b>To Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>To Type</em>' reference.
   * @see #setToType(Entity)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRelation_ToType()
   * @model
   * @generated
   */
  Entity getToType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Relation#getToType <em>To Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To Type</em>' reference.
   * @see #getToType()
   * @generated
   */
  void setToType(Entity value);

} // Relation
