/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MathIntLanguageStandaloneSetup extends MathIntLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new MathIntLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
